# Generated by Django 4.2.7 on 2024-01-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('sensor_data', '0002_measurement_time_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='location.location'),
        ),
    ]
