# Generated by Django 4.2.7 on 2023-12-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='lastSeen',
            field=models.DateTimeField(null=True),
        ),
    ]
