# Generated by Django 4.2.7 on 2024-01-24 23:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_device_hwid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='lastSeen',
        ),
        migrations.AddField(
            model_name='device',
            name='timeCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
