# Generated by Django 4.2.7 on 2024-03-21 19:24

import devices.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_remove_device_lastseen_device_timecreated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('tempThresh', models.FloatField()),
                ('deltaTurbThresh', models.FloatField()),
                ('deltaTempThresh', models.FloatField()),
                ('fluoroThresh', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='config',
            field=models.ForeignKey(default=devices.models.Config.getDefault, on_delete=django.db.models.deletion.PROTECT, to='devices.config'),
        ),
    ]
