# Generated by Django 4.2.7 on 2024-04-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_config_device_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='deltaFluoroThresh',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
