# Generated by Django 4.2.7 on 2024-03-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_config_device_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='turbThresh',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
