# Generated by Django 4.2.7 on 2024-03-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_config_device_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='config',
            old_name='temp_thresh',
            new_name='tempThresh',
        ),
        migrations.AddField(
            model_name='config',
            name='deltaTempThresh',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='deltaTurbThresh',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='fluoroThresh',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
